"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RecoilRoot } from "recoil";
import Header from "@/components/Header";
import React, { use, useState } from "react";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Timeline from "@/components/Timeline";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

// QueryClient 생성
const queryClient = new QueryClient();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <QueryClientProvider client={queryClient}>
      <RecoilRoot>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
              <div className="flex flex-col w-screen h-screen overflow-hidden">
                <Header />
                <div className="flex px-10 py-6 h-full overflow-y-auto">
                  {children}
                </div>
                <div className=" ">
                  <Timeline />
                </div>
              </div>
          </body>
        </html>
      </RecoilRoot>
    </QueryClientProvider>
  );
}
